from __future__ import annotations

import json
from pathlib import Path

from diffusion_longform_settings_sweep import DiffusionSettingsSweepConfig, run_settings_sweep


REPO_ROOT = Path(__file__).resolve().parents[2]


def targeted_bestpt_settings_panel():
    return [
        {
            "label": "best_mid_230_a",
            "note": "Safer bridge with modest style.",
            "t_start": 230,
            "t_start_end": 178,
            "reanchor_every": 4,
            "reanchor_t_start": 156,
            "guidance_scale": 1.80,
            "style_strength": 0.58,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.50,
            "source_mel_blend": 0.12,
            "hf_source_blend": 0.20,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_230_b",
            "note": "Slightly freer 230 preset.",
            "t_start": 230,
            "t_start_end": 178,
            "reanchor_every": 3,
            "reanchor_t_start": 156,
            "guidance_scale": 1.90,
            "style_strength": 0.64,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.48,
            "source_mel_blend": 0.10,
            "hf_source_blend": 0.18,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_245_a",
            "note": "Balanced 245 preset with stronger source anchor.",
            "t_start": 245,
            "t_start_end": 186,
            "reanchor_every": 4,
            "reanchor_t_start": 162,
            "guidance_scale": 1.85,
            "style_strength": 0.60,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.48,
            "source_mel_blend": 0.11,
            "hf_source_blend": 0.20,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_245_b",
            "note": "Balanced 245 preset with more style.",
            "t_start": 245,
            "t_start_end": 186,
            "reanchor_every": 4,
            "reanchor_t_start": 162,
            "guidance_scale": 1.95,
            "style_strength": 0.66,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.46,
            "source_mel_blend": 0.10,
            "hf_source_blend": 0.18,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_245_hf",
            "note": "245 preset with extra HF protection.",
            "t_start": 245,
            "t_start_end": 186,
            "reanchor_every": 4,
            "reanchor_t_start": 162,
            "guidance_scale": 1.90,
            "style_strength": 0.63,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.47,
            "source_mel_blend": 0.11,
            "hf_source_blend": 0.22,
            "hf_start_bin": 54,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_260_a",
            "note": "Style-forward 260 preset, still cautious.",
            "t_start": 260,
            "t_start_end": 194,
            "reanchor_every": 4,
            "reanchor_t_start": 168,
            "guidance_scale": 1.90,
            "style_strength": 0.62,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.46,
            "source_mel_blend": 0.10,
            "hf_source_blend": 0.19,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_260_b",
            "note": "Style-forward 260 preset with more guidance.",
            "t_start": 260,
            "t_start_end": 194,
            "reanchor_every": 4,
            "reanchor_t_start": 168,
            "guidance_scale": 2.00,
            "style_strength": 0.68,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.44,
            "source_mel_blend": 0.09,
            "hf_source_blend": 0.18,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_260_reanchor",
            "note": "260 preset with denser reanchor schedule.",
            "t_start": 260,
            "t_start_end": 194,
            "reanchor_every": 3,
            "reanchor_t_start": 162,
            "guidance_scale": 1.95,
            "style_strength": 0.66,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.45,
            "source_mel_blend": 0.10,
            "hf_source_blend": 0.18,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_260_hf",
            "note": "260 preset with extra HF guard.",
            "t_start": 260,
            "t_start_end": 194,
            "reanchor_every": 4,
            "reanchor_t_start": 168,
            "guidance_scale": 1.95,
            "style_strength": 0.66,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.45,
            "source_mel_blend": 0.10,
            "hf_source_blend": 0.21,
            "hf_start_bin": 54,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_275_a",
            "note": "Higher movement edge case.",
            "t_start": 275,
            "t_start_end": 202,
            "reanchor_every": 4,
            "reanchor_t_start": 172,
            "guidance_scale": 1.95,
            "style_strength": 0.68,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.44,
            "source_mel_blend": 0.09,
            "hf_source_blend": 0.18,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_275_b",
            "note": "Higher movement edge case with more style.",
            "t_start": 275,
            "t_start_end": 202,
            "reanchor_every": 3,
            "reanchor_t_start": 170,
            "guidance_scale": 2.00,
            "style_strength": 0.72,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.42,
            "source_mel_blend": 0.08,
            "hf_source_blend": 0.17,
            "hf_start_bin": 56,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
        {
            "label": "best_mid_275_hf",
            "note": "Higher movement edge case with stronger HF guard.",
            "t_start": 275,
            "t_start_end": 202,
            "reanchor_every": 3,
            "reanchor_t_start": 170,
            "guidance_scale": 1.95,
            "style_strength": 0.70,
            "prefix_blend": 1.0,
            "source_prefix_blend": 0.43,
            "source_mel_blend": 0.09,
            "hf_source_blend": 0.20,
            "hf_start_bin": 54,
            "mel_time_smooth": 3,
            "mel_freq_smooth": 0,
        },
    ]


def main() -> None:
    cfg = DiffusionSettingsSweepConfig(
        output_root=REPO_ROOT / "lab 3.1" / "outputs" / "diffusion_bestpt_targeted_sweep",
        run_dir=REPO_ROOT / "saves2" / "lab3_diffusion" / "run_d002",
        checkpoint_path=REPO_ROOT / "saves2" / "lab3_diffusion" / "run_d002" / "checkpoints" / "best.pt",
        n_songs=6,
        targets_per_song=1,
        source_seconds=36.0,
        chunk_seconds=3.0,
        overlap_seconds=0.5,
        n_frames=256,
        ddim_steps=50,
        assemble_domain="mel",
        device="auto",
        seed=328,
    ).materialize()
    summary = run_settings_sweep(cfg, targeted_bestpt_settings_panel())
    print(json.dumps(summary, indent=2, default=str))


if __name__ == "__main__":
    main()
